image: maven:latest

stages:
    - build

variables:
    MAVEN_CLI_OPTS: "--batch-mode"
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -DpackagerPhase=package"
    CORE: "remotelight-core"
    CLIENT: "remotelight-client"
    CTARGET: "remotelight-client/target"

cache:
    paths:
    - .m2/repository
    
before_script:
    - apt-get install -y zip
        
build:
    stage: build
    script:
    - mvn $MAVEN_CLI_OPTS package
    - zip -r $CTARGET/RemoteLight-Windows.zip $CTARGET/RemoteLight-Windows
    - zip -r $CTARGET/RemoteLight-Linux.zip $CTARGET/RemoteLight-Linux
    - zip -r $CTARGET/RemoteLight-MacOS.zip $CTARGET/RemoteLight-MacOS
    artifacts:
        paths:
        - $CLIENT/target/*.jar
        - $CLIENT/target/RemoteLight-*.zip
        exclude:
        - $CLIENT/target/remotelight-client-*.jar
        expire_in: 2 months
    only:
    - master